### ISSUE TITLE
Use as a library.

### ISSUE THREAD

**Issue by jcampbell05** [apngasm/apngasm#44]
How would I be able to use this as a library ? in my app ? Ideally I would like to compile the binary into my app, is it easy to do this ?

**Comment by Kagetsuki** [comment]
Yes! apngasm is split into two parts: apngasm-cli and libapngasm. There isn't extensive documentation but skim through the specs in test/apngtest.cpp for an example of pretty much every use case. Check the installation instructions for your platform as it's likely pre-compiled libraries are already available.

If you have any more questions feel free to ask - otherwise please close the issue.

**Comment by jcampbell05** [comment]
Okay yeah I can see it all :)

**Comment by Kagetsuki** [comment]
I'll close the issue for now. Feel free to reopen if if you have issues or anything. If you'd care to write some documentation or an article/blog as you go it would be much appreciated + give me a heads up so I can link it.
