### ISSUE TITLE
Multithreading?

### ISSUE THREAD

**Issue by SoniEx2** [apngasm/apngasm#48]
Is it possible to use multithreading to speed this up?

**Comment by Kagetsuki** [comment]
Perhaps to speed up generation of individual frames but unless you have a large number of large frames I doubt you'd see much improvement. Can you describe what you're doing that's taking so long?

**Comment by SoniEx2** [comment]
`rickroll.apng`

**Comment by Kagetsuki** [comment]
The extension is still .png, not .apng. You're saying you want to transcode part of the rickroll video?

**Comment by SoniEx2** [comment]
Not part, but the whole thing.

**Comment by Kagetsuki** [comment]
Short answer:
Use a video format, maybe something like webm.

Long answer:
You could do it but you need to remember this isn't a video codec. Literally every frame (other than duplicates) will be encoded as a full PNG. Compression is on the file, not (technically) cross-frame and compression is balanced for both speed and size so it's not the heaviest compression. Essentially you'll end up with a very big file which if you're embedding in a web browser will not load by frame and start playing during the load like a video would. You should probably look at webm instead of APNG.

As for transcoding and transcoding time, it's not impossible for sure but the encoder is certainly not optimized for something like this (and since this is not a very good application for APNG it probably shouldn't be). Though I expect transcoding time would be comparable to other raw codecs transcoding in single-thread. BUT if I'm not mistaken APNGAsm handles all frames in memory, compared to a video codec the encoder could be intensely memory heavy.

If you absolutely insist on encoding this in APNG I would like to note there is a frame concatenator which lets you combine two APNG files - so you could probably break apart your encoding into several processes, then concatenate the results. I suspect that due to compression and decompression and just general disk-to-memory and memory-to-disk IO, along with initialization delay etc. the net result would be a longer overall transcode time.

**Comment by SoniEx2** [comment]
> Compression is on the file, not (technically) cross-frame and compression is balanced for both speed and size so it's not the heaviest compression.

So you're basically storing all the frames instead of using the cross-frame compression options APNG gives you... am I correct?

**Comment by Kagetsuki** [comment]
I think you're confusing APNG cross frame compression with the kind of compression you'd see in a video codec. APNG has much more basic compression scheme. In terms of animated images it's about as good as you can get, but when you're comparing it to video compression it's not going to stack up very well. To put it more bluntly, APNG compression is for shorter, smaller, high quality animations VS webm and the like are for mid to long mid sized mixed-quality videos.

Using APNG for video is like chopping meat with a fruit knife - it can be done and it can be done well and you may even get a higher quality cut, but a cleaver will get the job done quicker and more efficiently.

**Comment by Kagetsuki** [comment]
Actually let me give a more technical description. In video compression you basically have a base frame and you have "derivative" frames that take parts of that base frame and have descriptors of how things change. These descriptors are different by codec but they basically don't replicate a frame. The reason many videos can be streamed or played when only part of their data is available is because ideal base frames are calculated and then frames after them up till the next base frame will use these descriptors. As long as you have the base frame you can start playing each frame after that by its descriptors. On top of that chunks of video will be compressed, and sometimes the whole video will be compressed with a master compression block or some other scheme. So not only do you have reduced weight in the data of each frame you also have a master compression over the whole data set.

APNG on the other hand takes all the frames, [as the initial part of compression] reduces repetitive data, then compresses everything else more or less like standard data. You [usually/technically] need the whole file to decompress and play it so while streaming may be possible on some files there is never any guarantee nor is there really an accepted method to do so.

**Comment by Kagetsuki** [comment]
@SoniEx2 I'm going to close out the issue - feel free to re-open it if you have a specific reason to.

**Comment by SoniEx2** [comment]
I can't reopen my own issues if they were closed by someone other than me unless I have contributor status.

If you feel like this is best for the project then I respect your decision.

**Comment by Kagetsuki** [comment]
@SoniEx2 To actually add multi-threading would come with little real-world benefit and a lot of complexity so it's definitely not something I have any particular intention of trying to tackle. My recommendation is to either just make a short clip or to use an actual video codec/format. Thanks for your interest though!
