### ISSUE TITLE
Add documentation on how to static link dependencies

### ISSUE THREAD

**Issue by mlundela** [apngasm/apngasm#57]
It would be nice to build apngasm as a standalone binary to be used in environments like aws lambda.

**Comment by Kagetsuki** [comment]
I'm absolutely certain we at some point had static builds working, but when I checked just now I couldn't seem to generate one. I'm positive it can be built static as I'm sure we've done it before and there are clearly traces of it in the CMake files, but I have a suspicion it was accidentally removed in a re-factor/cleanup. Let me dig into this a little more.

As for AWS Lambda, you should be able to vendorize a dynamic libapngasm by grabbing a container, doing a build by hand, and copying out the .so files etc. and packaging them up.

**Comment by Kagetsuki** [comment]
I just re-read your comment and realized you asked for a "standalone binary", not a "static library". I'll consider the viability of this but half of the reason for version 3 was to break out apngasm features into a library. We've decided we should have a proper static build chain anyway and we already started working on it and that should make wrapping up everything into a portable bin a little easier. I'll update this issue with our progress.

**Comment by Kagetsuki** [comment]
@mlundela Can you please confirm why a static build is necessary? We did some static build tests and found a few issues - it would likely be best if we just stuck with dynamic builds.

**Comment by mlundela** [comment]
I tried package all the .so files, but then it still reported linking issues. Unfortunately logs are gone, but if you need them I can try to reproduce it.

**Comment by Kagetsuki** [comment]
I suspect you didn't package them with other dependencies? If you have the time the logs would probably make it more apparent what the issue is.

**Comment by mlundela** [comment]
Ok, so I managed to reproduce the point where I gave up and went for the older version. The issue is more related to limitations on AWS Lambda, I guess. Maybe you know a solution? The total size of the zip file is also very large when I include all the dynamically linked libraries. 


```
(! 704) (master)# ls -alR .
total 40
0 drwxr-xr-x   8 mads  staff   272B Nov 23 22:38 ./
0 drwxr-xr-x   8 mads  staff   272B Nov 23 16:05 ../
8 -rw-r--r--   1 mads  staff   316B Nov 23 22:28 Makefile
8 lrwxr-xr-x   1 mads  staff    35B Nov 23 22:28 apngasm@ -> ../../binaries/apngasm/dist/apngasm
8 -rw-r--r--   1 mads  staff   155B Nov 23 22:29 function.dev.json
8 -rw-r--r--   1 mads  staff   790B Nov 23 18:07 index.js
0 drwxr-xr-x  13 mads  staff   442B Nov 23 22:29 lib/
8 -rw-r--r--   1 mads  staff   239B Nov 23 17:58 package.json

./lib:
total 66728
    0 drwxr-xr-x  13 mads  staff   442B Nov 23 22:29 ./
    0 drwxr-xr-x   8 mads  staff   272B Nov 23 22:38 ../
 1024 -rw-r--r--   1 mads  staff   511K Nov 23 22:29 libapngasm.so
  192 -rw-r--r--   1 mads  staff    95K Nov 23 22:29 libboost_filesystem.so.1.58.0
 1008 -rw-r--r--   1 mads  staff   503K Nov 23 22:29 libboost_program_options.so.1.58.0
 2120 -rw-r--r--   1 mads  staff   1.0M Nov 23 22:29 libboost_regex.so.1.58.0
   32 -rw-r--r--   1 mads  staff    14K Nov 23 22:29 libboost_system.so.1.58.0
50616 -rw-r--r--   1 mads  staff    25M Nov 23 22:29 libicudata.so.55
 4880 -rw-r--r--   1 mads  staff   2.4M Nov 23 22:29 libicui18n.so.55
 3200 -rw-r--r--   1 mads  staff   1.6M Nov 23 22:29 libicuuc.so.55
  296 -rw-r--r--   1 mads  staff   146K Nov 23 22:29 libpng12.so.0
  296 -rw-r--r--   1 mads  staff   146K Nov 23 22:29 libpng12.so.0.54.0
 3064 -rw-r--r--   1 mads  staff   1.5M Nov 23 22:29 libstdc++.so.6
```

The stderr logs when running apngasm on Lambda:
```
/aws/lambda/io_apng 2016-11-23T21:33:52.652Z	870496a0-b1c4-11e6-8cc9-f3df91320d1d	stderr: apngasm: /usr/local/lib64/node-v4.3.x/lib/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by apngasm)
apngasm: /usr/local/lib64/node-v4.3.x/lib/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /var/task/lib/libapngasm.so)
apngasm: /usr/local/lib64/node-v4.3.x/lib/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /var/task/lib/libboost_program_options.so.1.58.0)
apngasm: /usr/local/lib64/node-v4.3.x/lib/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /var/task/lib/libboost_regex.so.1.58.0)
apngasm: /usr/local/lib64/node-v4.3.x/lib/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /var/task/lib/libboost_filesystem.so.1.58.0)
apngasm: /usr/local/lib64/node-v4.3.x/lib/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /var/task/lib/libboost_system.so.1.58.0)
```

**Comment by Kagetsuki** [comment]
First off:
```
The total size of the zip file is also very large when I include all the dynamically linked libraries
```
You'd end up with something about the equivalent of that with a full static build since you're basically rolling all that up into a big ball. If you're worried about size then the answer is almost invariably going to be a dynamic build.

The errors you're getting and the fact that you're bundling things like libstdc++ imply to me that you're not compiling on/for your target but rather just compiling locally and putting everything into a zip, which I seriously doubt would actually work even if you had a static binary.

Ideally what you should do is:
1. Grab a container image of whatever container you're using on your target platform
2. Check what dependencies are available
3. Either add the packages for the remaining dependencies to your container image or grab sources and compile yourself
4. Compile in the container, package the resulting .so, bin, and any dependency .so's you built.

Following those steps it is highly unlikely you would be bundling things like libstdc++, libicu~, and probably libpng as well since it's such a common dependency I seriously doubt it would be missing from a container image unless it was very very minimal. libboost~ I'd bet you'll end up packaging.

Can you try doing a native compile on a lambda [build] container?
