### ISSUE TITLE
Clarification on --skip flag

### ISSUE THREAD

**Issue by dannyking** [apngasm/apngasm#82]
I'm using the apngasm CLI v3.1.6 on mac and I'm having unexpected results with the "--save" flag. 

From reading the --help text "Skip the first frame. When animation is not supported the first frame is shown." I assumed that using the --skip flag would include the first image frame in the apng file output, but would instruct browsers that support apng to skip that frame in the animation, and non-supporting browsers would just show the first frame. Is that correct?

Or does --skip simply tell apngasm to not include the first frame in the apng output?

I'm attaching three images here for illustration:

- first-frame.png - the (non apng) png image used for the first frame.

![first-frame](https://user-images.githubusercontent.com/333164/120249927-4ca50000-c231-11eb-85d8-0b4cb679cd48.png)

- without-skip.png 
    - created using: apngasm --force --loops 1 --output without-skip.png $(ls *.png | sort -V)
    - includes the first frame, but the first frame also renders in chrome during the animation 
    - e.g. if you open this image file in a chrome tab and hit refresh, you'll see the first frame flash (unexpected behavior)

![without-skip](https://user-images.githubusercontent.com/333164/120249874-1ebfbb80-c231-11eb-8043-80e5aef162f6.png)

- with-skip.png 
    - created using: apngasm --skip --force --loops 1 --output with-skip.png $(ls *.png | sort -V)
    - Does not include the first frame in the apng output, and so in non-supported renderers (e.g. thumbnails in mac finder or when pasting in iphone imessage) the wrong static frame is shown
  
![with-skip](https://user-images.githubusercontent.com/333164/120249877-241d0600-c231-11eb-8040-d4a610e09a67.png)

Am I simply misunderstanding how the --save flag should work, or is this a bug?

I would like to be able to export an apng that falls back to the first frame in unsupported environments (like imessage), but which doesn't show that frame in supported environments (like chrome).

P.S. wonderful software, thank you!

**Comment by dannyking** [comment]
Any updates would be greatly appreciated here, thanks!

**Comment by Kagetsuki** [comment]
Sorry for the delay.

--skip skips the first frame of the animation on software/browsers that support animated PNG.

Some browsers and software don't support APNG. The APNG format saves the first frame like a normal PNG image and then has all the extra frames and animation control information in an "extended data" sort of part of the file. So when you have an image that may be viewed in software that doesn't support animation that first frame is the only thing that's going to be shown, so instead of just showing the first frame of the animation you may want to insert a frame that would be shown instead of the animation, and in that case you wouldn't want to show that frame as part of the animation, so in that case you'd use the --skip flag.
