### ISSUE TITLE
Proper Abstract

### ISSUE THREAD

**Issue by kungfooman** [apngasm/apngasm#83]
I just saw this in my GitHub feed and the current abstract is useless:

> The next generation of apngasm, the APNG Assembler.

Is it another Assembler obfuscator? Saving code in images? Can APNG execute code by now?! A = Advanced?!

I had to skim through the man file to finally find a little bit more information:

> apngasm can assemble or dis-assemble Animated PNG files.

Oh, an image format... I see

**Comment by Kagetsuki** [comment]
APNG is a format, and apngasm "assembles" APNG images, just as described. I'm not sure why you are having trouble parsing the abstract; but the abstract is fine as is.

I would also recommend you not make comments like this in the future. Announcing to the world you don't understand what a project is only clutters up the issues.

**Comment by Kagetsuki** [comment]
APNG is an image format and apngasm "assembles" APNG images. You not knowing what an APNG was does not mean there is a problem with the abstract, it means you were unable to parse what the abstract meant because of your lack of knowledge.

I will take your suggestion under advisement and try to add clarification of what APNG is in the abstract - though generally if someone wasn't specifically looking to handle APNG files I'm not sure why the would even seek out this project.

Also, please be careful of how you word your comments. I'm assuming your English is limited so I'll give you the benefit of the doubt, but your comment comes off as a little arrogant and argumentative.
